version: '3'
services:
  nestjs-app:
    build:
      context: . # Path to your Nest.js app's Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql-db
    environment:
      DATABASE_HOST: mysql-db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: app_schema

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_schema
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:


